/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_eliasgiron;

import java.awt.Color;
import java.math.MathContext;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author EliasGZ
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_ingresar = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_apellido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tf_idusuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pf_contrasena = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        tf_edad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jb_color = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tf_mazos = new javax.swing.JTextField();
        jb_agregar = new javax.swing.JButton();
        jb_cerrar = new javax.swing.JButton();
        jd_agregarcartas = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_cartas = new javax.swing.JTree();
        cb_cartas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jb_agregarmazo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_nombrecarta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_dano = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_puntos = new javax.swing.JTextField();
        menu_popup = new javax.swing.JPopupMenu();
        jmi_agregarcarta = new javax.swing.JMenuItem();
        jd_iniciarsesion = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        tf_usuariocreado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pf_contrasenacreada = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_sistema = new javax.swing.JMenu();
        jmi_crearcuenta = new javax.swing.JMenuItem();
        jmi_ingresar = new javax.swing.JMenuItem();
        jmi_agregarcartas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmi_agregarclan = new javax.swing.JMenuItem();
        jmi_uniraclan = new javax.swing.JMenuItem();
        jm_ingresar = new javax.swing.JMenu();

        jLabel10.setText("Nombre");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Crear Usuario");

        jLabel12.setText("Apellido");

        jLabel13.setText("Id de usuario ");

        jLabel14.setText("Contraseña");

        jLabel15.setText("Fecha de Nacimiento");

        jLabel16.setText("Edad");

        jLabel17.setText("Color Favorito");

        jb_color.setText("Color");
        jb_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_colorMouseClicked(evt);
            }
        });

        jLabel18.setText("Mazos");

        jb_agregar.setText("Agregar Usuario");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        jb_cerrar.setText("Cerrar Ventana");
        jb_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel11)
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(44, 44, 44))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel18))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_apellido)
                    .addComponent(tf_nombre)
                    .addComponent(tf_idusuario)
                    .addComponent(pf_contrasena)
                    .addComponent(jd_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_color, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_mazos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jb_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_idusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(pf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jb_color, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tf_mazos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jb_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_ingresarLayout = new javax.swing.GroupLayout(jd_ingresar.getContentPane());
        jd_ingresar.getContentPane().setLayout(jd_ingresarLayout);
        jd_ingresarLayout.setHorizontalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_ingresarLayout.setVerticalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_agregarcartas.setBackground(new java.awt.Color(255, 51, 51));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Cartas");
        jt_cartas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_cartas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_cartasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_cartas);

        cb_cartas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minipekka", "Montapuerco", "Golem", "Leñador", "Dragon Infernal", "Dragon", "Gigante Noble", "Pandilla de Duendes" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Agregar Carta");

        jLabel1.setText("Cartas");

        jb_agregarmazo.setBackground(new java.awt.Color(51, 0, 51));
        jb_agregarmazo.setText("Agregar Mazo");
        jb_agregarmazo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarmazoMouseClicked(evt);
            }
        });

        jLabel3.setText("Nombre de Carta");

        jLabel4.setText("Daño");

        jLabel5.setText("Puntos de vida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(142, 142, 142))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nombrecarta)
                    .addComponent(cb_cartas, 0, 170, Short.MAX_VALUE)
                    .addComponent(tf_dano)
                    .addComponent(tf_puntos))
                .addGap(324, 324, 324))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jb_agregarmazo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombrecarta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_cartas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_dano, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jb_agregarmazo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jd_agregarcartasLayout = new javax.swing.GroupLayout(jd_agregarcartas.getContentPane());
        jd_agregarcartas.getContentPane().setLayout(jd_agregarcartasLayout);
        jd_agregarcartasLayout.setHorizontalGroup(
            jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jd_agregarcartasLayout.setVerticalGroup(
            jd_agregarcartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jmi_agregarcarta.setText("Agregar Carta");
        jmi_agregarcarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarcartaActionPerformed(evt);
            }
        });
        menu_popup.add(jmi_agregarcarta);

        jLabel6.setText("Usuario");

        jLabel7.setText("Contraseña");

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_iniciarsesionLayout = new javax.swing.GroupLayout(jd_iniciarsesion.getContentPane());
        jd_iniciarsesion.getContentPane().setLayout(jd_iniciarsesionLayout);
        jd_iniciarsesionLayout.setHorizontalGroup(
            jd_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_iniciarsesionLayout.createSequentialGroup()
                .addGroup(jd_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_iniciarsesionLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jd_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(21, 21, 21)
                        .addGroup(jd_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usuariocreado)
                            .addComponent(pf_contrasenacreada, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addGroup(jd_iniciarsesionLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jd_iniciarsesionLayout.setVerticalGroup(
            jd_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_iniciarsesionLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jd_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_usuariocreado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jd_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pf_contrasenacreada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_sistema.setText("Sistema");

        jmi_crearcuenta.setText("Crear Usuario");
        jmi_crearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearcuentaActionPerformed(evt);
            }
        });
        jm_sistema.add(jmi_crearcuenta);

        jmi_ingresar.setText("Ingresar Usuario");
        jmi_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ingresarActionPerformed(evt);
            }
        });
        jm_sistema.add(jmi_ingresar);

        jmi_agregarcartas.setText("Agregar Cartas");
        jmi_agregarcartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregarcartasActionPerformed(evt);
            }
        });
        jm_sistema.add(jmi_agregarcartas);

        jMenu1.setText("Clan");
        jMenu1.setEnabled(false);

        jmi_agregarclan.setText("Agregar Clan");
        jMenu1.add(jmi_agregarclan);

        jmi_uniraclan.setText("Unirse a Clan");
        jMenu1.add(jmi_uniraclan);

        jm_sistema.add(jMenu1);

        jMenuBar1.add(jm_sistema);

        jm_ingresar.setText("Ingresar");
        jMenuBar1.add(jm_ingresar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        // TODO add your handling code here:
        String nombre;
        String apellido;
        String nombreusuario;
        String contraseña;
        Date fecha;
        Color favorito;
        int mazos;
        long edad = 0;
        try {
            nombre = tf_nombre.getText();
            apellido = tf_apellido.getText();
            nombreusuario = tf_apellido.getText();
            contraseña = pf_contrasena.getText();
            fecha = jd_fecha.getDate();
            favorito = jb_color.getBackground();
            mazos = 3;
            tf_mazos.setText("3");
            Usuario s = new Usuario(nombre, apellido, nombreusuario, contraseña, fecha, favorito, mazos, edad);
            edad = ((new Date()).getTime() - s.getFecha().getTime()) / (1000 * 60 * 60 * 24);
            tf_edad.setText(Long.toString(edad));
            s.setEdad(edad);
            usuarios.add(s);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error, intente mas tarde");

        }
        tf_nombre.setText("");
        tf_apellido.setText("");
        tf_apellido.setText("");
        pf_contrasena.setText("");
        jb_color.setBackground(Color.WHITE);
        tf_mazos.setText("");

    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jmi_crearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearcuentaActionPerformed
        jd_ingresar.setModal(true);
        jd_ingresar.pack();
        jd_ingresar.setLocationRelativeTo(this);
        jd_ingresar.setVisible(true);

    }//GEN-LAST:event_jmi_crearcuentaActionPerformed

    private void jmi_agregarcartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarcartasActionPerformed
        jd_agregarcartas.setModal(true);
        jd_agregarcartas.pack();
        jd_agregarcartas.setLocationRelativeTo(this);
        jd_agregarcartas.setVisible(true);

    }//GEN-LAST:event_jmi_agregarcartasActionPerformed

    private void jb_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_colorMouseClicked
        // TODO add your handling code here:
        jb_color.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_jb_colorMouseClicked

    private void jb_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cerrarMouseClicked
        // TODO add your handling code here:
        jd_ingresar.setVisible(false);

    }//GEN-LAST:event_jb_cerrarMouseClicked

    private void jb_agregarmazoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarmazoMouseClicked

        DefaultTreeModel m = (DefaultTreeModel) jt_cartas.getModel();
        DefaultMutableTreeNode r = (DefaultMutableTreeNode) m.getRoot();
        if (cont <= 3) {
            DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Mazo());
            r.add(p);
            cont++;
        } else {
            JOptionPane.showMessageDialog(jd_agregarcartas, "No puede agregar mas de 3 mazos");
        }
        m.reload();

    }//GEN-LAST:event_jb_agregarmazoMouseClicked

    private void jt_cartasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cartasMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            int row = jt_cartas.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_cartas.setSelectionRow(row);

            Object v1
                    = jt_cartas.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Mazo) {
                mazo_seleccionado = (Mazo) nodo_seleccionado.getUserObject();
                menu_popup.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_jt_cartasMouseClicked

    private void jmi_agregarcartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregarcartaActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) jt_cartas.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode nodo_carta;
        nodo_carta = (DefaultMutableTreeNode) cb_cartas.getSelectedItem();
        DefaultMutableTreeNode nombre;
        nombre = new DefaultMutableTreeNode(tf_nombrecarta.getText());
        nodo_carta.add(nombre);
        modelo.reload();
        DefaultMutableTreeNode puntos = new DefaultMutableTreeNode(tf_puntos.getText());
        nodo_carta.add(puntos);
        DefaultMutableTreeNode Dano;
        Dano = new DefaultMutableTreeNode(tf_dano.getText());
        DefaultMutableTreeNode Velocidad;
        DefaultMutableTreeNode objetivo;
        DefaultMutableTreeNode Coste;
        DefaultMutableTreeNode tipo;
        if (cb_cartas.getSelectedItem().toString().equals("Minipekka")) {
            Velocidad = new DefaultMutableTreeNode("Alta");
            objetivo = new DefaultMutableTreeNode("Terrestre");
            tipo = new DefaultMutableTreeNode("Especial");
        } else if (cb_cartas.getSelectedItem().toString().equals("Montapuerco")) {
            Velocidad = new DefaultMutableTreeNode("Alta");
            objetivo = new DefaultMutableTreeNode("Terrestre");

            tipo = new DefaultMutableTreeNode("Especial");
        } else if (cb_cartas.getSelectedItem().toString().equals("Golem")) {
            Velocidad = new DefaultMutableTreeNode("Baja");
            objetivo = new DefaultMutableTreeNode("Terrestre");
            tipo = new DefaultMutableTreeNode("Epica");
        } else if (cb_cartas.getSelectedItem().toString().equals("Leñador")) {
            Velocidad = new DefaultMutableTreeNode("Alta");
            objetivo = new DefaultMutableTreeNode("Terrestre");
            tipo = new DefaultMutableTreeNode("Legendaria");
        } else if (cb_cartas.getSelectedItem().toString().equals("Dragon Infernal")) {
            Velocidad = new DefaultMutableTreeNode("Media");
            objetivo = new DefaultMutableTreeNode("Aereos y Terrestres");
            tipo = new DefaultMutableTreeNode("Legendaria");
            
        } else if (cb_cartas.getSelectedItem().toString().equals("Dragon")) {
            Velocidad = new DefaultMutableTreeNode("Media");
            objetivo = new DefaultMutableTreeNode("Aereos y Terrestres");
            tipo = new DefaultMutableTreeNode("Epica");
        } else if (cb_cartas.getSelectedItem().toString().equals("Gigante Noble")) {
            Velocidad = new DefaultMutableTreeNode("Media");
            objetivo = new DefaultMutableTreeNode("Terrestres");
            tipo = new DefaultMutableTreeNode("Comun");
        } else if (cb_cartas.getSelectedItem().toString().equals("Pandilla de Duendes")) {
            Velocidad = new DefaultMutableTreeNode("Alta");
            objetivo = new DefaultMutableTreeNode("Aereos y Terrestres");
            tipo = new DefaultMutableTreeNode("Comun");
        }
        modelo.reload();
    }//GEN-LAST:event_jmi_agregarcartaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getNombreusuario().equals(tf_usuariocreado.getText()) && usuarios.get(i).getContraseña().equals(pf_contrasenacreada.getText())) {
                JOptionPane.showMessageDialog(jd_iniciarsesion, "Bienvenido Jugador");
            } else {
                JOptionPane.showMessageDialog(jd_iniciarsesion, "El usuario o contraseña son incorrectos");
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jmi_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ingresarActionPerformed
        // TODO add your handling code here:
        jd_iniciarsesion.setModal(true);
        jd_iniciarsesion.pack();
        jd_iniciarsesion.setLocationRelativeTo(this);
        jd_iniciarsesion.setVisible(true);
    }//GEN-LAST:event_jmi_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_cartas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_agregarmazo;
    private javax.swing.JButton jb_cerrar;
    private javax.swing.JButton jb_color;
    private javax.swing.JDialog jd_agregarcartas;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private javax.swing.JDialog jd_ingresar;
    private javax.swing.JDialog jd_iniciarsesion;
    private javax.swing.JMenu jm_ingresar;
    private javax.swing.JMenu jm_sistema;
    private javax.swing.JMenuItem jmi_agregarcarta;
    private javax.swing.JMenuItem jmi_agregarcartas;
    private javax.swing.JMenuItem jmi_agregarclan;
    private javax.swing.JMenuItem jmi_crearcuenta;
    private javax.swing.JMenuItem jmi_ingresar;
    private javax.swing.JMenuItem jmi_uniraclan;
    private javax.swing.JTree jt_cartas;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JPasswordField pf_contrasena;
    private javax.swing.JPasswordField pf_contrasenacreada;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_dano;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_idusuario;
    private javax.swing.JTextField tf_mazos;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombrecarta;
    private javax.swing.JTextField tf_puntos;
    private javax.swing.JTextField tf_usuariocreado;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> usuarios = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    ArrayList<Usuario> integrantes = new ArrayList();
    int cont = 0;
    Mazo mazo_seleccionado;
}
